### ISSUE TITLE
sonar 4.2 support

### ISSUE THREAD

**Issue by bikeonastick** [GoDaddy-Hosting/ruby-sonar-plugin#2]
This plugin does not work with sonar 4.2. Are you working on an update to it? If not, I have some ideas and will fork and build one. I didn't want to do that, though, if you are already working on it.

**Comment by bsclifton** [comment]
This plugin is now compatible with Sonar 4.5.5 LTS!  I know it's been over a year, but if the plugin is still useful for you, please consider giving it a try.  Thanks! :smile:
